# Generated by Django 6.0.2 on 2026-02-23 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('topics', models.TextField(blank=True, null=True)),
                ('current_question_number', models.IntegerField(default=0)),
                ('total_score', models.FloatField(default=0)),
                ('stage', models.CharField(choices=[('waiting_for_start', 'Waiting For Start'), ('waiting_for_role', 'Waiting For Role'), ('waiting_for_topics', 'Waiting For Topics'), ('interview_started', 'Interview Started'), ('waiting_for_answer', 'Waiting For Answer'), ('completed', 'Completed')], default='waiting_for_start', max_length=50)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('user_answer', models.TextField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interviews.interviewsession')),
            ],
        ),
    ]
