# Generated by Django 6.0.2 on 2026-02-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewquestion',
            options={'ordering': ['question_number']},
        ),
        migrations.AlterModelOptions(
            name='interviewsession',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='ai_evaluation',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='answered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='max_score',
            field=models.FloatField(default=20),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='question_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='question_type',
            field=models.CharField(choices=[('technical', 'Technical'), ('behavioral', 'Behavioral'), ('situational', 'Situational'), ('coding', 'Coding')], default='technical', max_length=20),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='difficulty_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='duration_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='max_score',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='percentage_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='total_questions',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='interviewquestion',
            name='score',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
