# Generated by Django 6.0.2 on 2026-03-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_cvinterviewsession_cvinterviewquestion_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='mode',
            field=models.CharField(blank=True, choices=[('random', 'Random Topics'), ('single', 'Single Topic')], default='random', max_length=20, null=True),
        ),
    ]
